services:
  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.7
    restart: unless-stopped
    depends_on:
      - evolution_redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - evolution-net
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          memory: 512M

  evolution_redis:
    image: redis:latest
    container_name: evolution_redis
    hostname: evolution_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - evolution-net
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  evolution-net:
    driver: bridge
